### ISSUE TITLE
Seperate paragraph into sntences

### ISSUE THREAD

**Issue by zettam** [wooorm/parse-english#10]
Very nice library.
I'm looking for a way to use this to seperate a paragraph into sentences.
How would it be possible?

Thank you

**Comment by wooorm** [comment]
Thanks,

*   Take a look at [node-sentence-tools](https://github.com/beaugunderson/node-sentence-tools), which uses parse-english to focus mainly on sentences;
*   If you’re going your own way, take a look at [nlcst-to-string](https://github.com/wooorm/nlcst-to-string), which stringifies nodes back into english;
*    Also, maybe just try to look at the output generated by **parse-english**, it’s pretty straightforward :)

Hope that helps!
