### ISSUE TITLE
Gets confused on decimal numbers without zeros

### ISSUE THREAD

**Issue by Ravenstine** [wooorm/parse-english#19]
For example:
```
The MPAA's annual report showed a global increase of .5 percent in ticket sales from 2015. While China, the world's second-largest market after the U.S., has long been a priority of Hollywood, it dropped 3 percent last year with $6.6 billion in ticket sales.
```

The result I get is these two separate "sentences".

```
The MPAA's annual report showed a global increase of .
```
```
5 percent in ticket sales from 2015. While China, the world's second-largest market after the U.S., has long been a priority of Hollywood, it dropped 3 percent last year with $6.6 billion in ticket sales.
```

It seems like decimal numbers where the zero is absent get mistaken as a full-stop.  Similarly, when a zero is applied to the number, the output is the entire paragraph as a single sentence.  I figured out that's because the parser is mistaking `2015.` as something other than a full-stop.  When anything is added to the end of the sentence, or if `2015` is removed, the three sentences are parsed out correctly.

Unless I'm forgetting something, decimal numbers would be pretty simple to adjust for since it looks like parse-english will only consider a `.` a full stop if there is at least one whitespace following it.  Since it's pretty common for sentences to end with a year number, it may have to be a combination of "is this a year?" and "is the first character following the period a capital letter or number?"

**Comment by wooorm** [comment]
Thanks! Fixed and released, a simple `npm update` should do the trick (as it’s a bug fix in a dependency, `parse-latin@4.0.1`).
