### ISSUE TITLE
Problem with lowercase sentences

### ISSUE THREAD

**Issue by pkrumins** [wooorm/parse-english#20]
Hi Titus,

Thanks for creating this awesome library!

I tried using it to parse my text into sentences but unfortunately ran in an issue where sentences that are written in lowercase are all parsed as a single sentence. For example, two or more sentences like `hello world. this is fun.` are parsed as a single sentence.

I digged into source code and found that most likely `parse-latin`'s `merge-initial-lower-case-letter-sentences` plugin merges together lowercase sentences as a single sentence. I tried finding options that would disable this plugin but were unable to do it.

The problem that I'm solving is fixing the capitalization of English text. The approach that I'm taking is splitting the text into sentences and then capitalizing the first letter but as all input sentences can be lowercase, I am unable to get the job done with this library as I only get one `SentenceNode` for the entire input text.

Could you please advise how to disable the `merge-initial-lower-case-letter-sentences` plugin or any other approach that I could take to solve the problem? Any help appreciated!

Peter

**Comment by wooorm** [comment]
Hi Peter!

Hmmm, that’s difficult: the most important heuristic to figure out what the sentences are, is exactly that sentence casing, for parse-latin.

I don’t think there’s a way to turn `merge-initial-lower-case-letter-sentences` off, it may be a good idea that I’m :+1: for, but I don’t think turning it off will help you, and instead lead to poor results.

It’s been awhile, but differentiating between sentences is hard! Sentence case gets you most the way there, but then there are still exceptions. Without casing, it’s much harder to do. Expecting proper casing, this project should figure out almost all cases, but without casing, I don’t think you can get  good results 🤔

**Comment by wooorm** [comment]
What is the input data? Is it mostly properly cases with a few exceptions, or..?

**Comment by pkrumins** [comment]
Thanks for the explanation! I didn't realize that letter case was part of heuristics. The input data in my application can have mixed case and often is all lowercase. I'll try deleting the `merge-initial-lower-case-letter-sentences` plugin directly from module's code and see what happens!

**Comment by wooorm** [comment]
Let me know how that goes!

**Comment by wooorm** [comment]
Still interested to hear how it’s going!

I am going to close this though, because I don’t really see how this project could work well without this important heuristic.
