### ISSUE TITLE
Considers list item marker part of the sentence

### ISSUE THREAD

**Issue by astoilkov** [wooorm/parse-english#22]
The algorithm considers `- ` part of the sentence: `- Here's to the crazy ones. The misfits.`

I am not sure you are willing to add this type of check as part of the library. From my biased point of view I think it's worth it.

**Comment by wooorm** [comment]
Well, it is, if you’re dealing with natural language?

Looks like you have markup/markdown. Can you use [remark](https://github.com/remarkjs/remark)?

**Comment by astoilkov** [comment]
Yes, we have a markdown editor. By using remark do you mean parsing the content and excluding markers from it?

**Comment by wooorm** [comment]
Remark is like this project, but for markdown. So it understands all the markdown syntax. And it integrates with retext, which in turn uses this project, so you could *also* access this syntax tree!

**Comment by astoilkov** [comment]
That will work. Thanks! Feel free to close this if you decide is out of scope.

**Comment by wooorm** [comment]
Yeah, I think that’s what I’m going with. I feel it’s syntax, and that that’s something for other projects.

Good luck!
